name: Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Test new thing
      uses: 8BitJonny/gh-get-current-pr@2.2.0
      id: PR
    - run: echo ${{ steps.PR.outputs.pr_title }}
    - run: echo ${{ github.event.pull_request.body }}
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_TOKEN }}
        repository: Hageromo/cypress
        event-type: cart-tests
        client-payload: '{"title": "Test title", "main": "${{ github.head_ref }}"}, "new": "${{ steps.PR.outputs.pr_title }}"'
        
