name: Test

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
  
jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: ${{ ((github.event.pull_request.merged == true) && (github.event.pull_request.base.ref == 'main')) || (github.event_name == 'workflow_dispatch') }}
    steps:
    - run: echo ${{ github.event.push.body }}
    - run: echo ${{ github.event.pull_request.body }}
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_TOKEN }}
        repository: Hageromo/cypress
        event-type: cart-tests
        client-payload: '{"title": ${{ github.event.pull_request.title }}"}'
